### ISSUE TITLE
Correzione PdP

### ISSUE THREAD

**Issue by amemeggio** [techsweave/documentation#15]
- [x] sistemare attualizzazione dei rischi;
- [x] sistemare incrementi in tabella;
- [x] sistemare diagrammi gantt in base a incrementi;
- [x] sistemare ripianificazione delle attività future.

**Comment by nicoloGiaccone** [comment]
Ho aggiunto una tabella che va a mappare gli incrementi che andremo a svolgere durante la fase di progettazione e codifica di dettaglio, ed ho fatto alcune correzzioni sintattiche

**Comment by nicoloGiaccone** [comment]
Iniziata la pianificazione degli incrementi.
Ho aggiunto:
- obbiettivi;
- periodo;
- ruoli attivi(da rivedere)

Devo aggiungere le varie attività svolte e i diagrammi di Gantt

**Comment by nicoloGiaccone** [comment]
Completata pianificazione incrementi, parti mancanti incrementi:
- [x] ristrutturare tabella incrementi RP;
- [x] fare tabella incrementi RA.

**Comment by nicoloGiaccone** [comment]
Ho ristrutturato la tabella per gli incrementi RP ed ho aggiunto la loro pianificazione

**Comment by amemeggio** [comment]
aggiunti diagrammi gantt, tabelle e grafici preventivo e consuntivo di incrementi fase RQ
